---
title: "Linear models"
author: "Amrutha Banda"
date: "2025-11-06"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(p8105.datasets)

```

Load the NYC airbnb data

```{r}
data("nyc_airbnb")

```


Look at the data/ do some cleaning
```{r}
nyc_airbnb = 
  nyc_airbnb |> 
  mutate(stars = review_scores_location / 2) |> 
  rename(
    borough = neighbourhood_group) |> 
  filter(borough != "Staten Island") |> 
  select(price, stars, borough, neighbourhood, room_type)
```


Do regression!!
```{r}
fit= lm( price~ stars+ borough, data = nyc_airbnb)
```

Do some additional cleaning then refit 

```{r}
nyc_airbnb= 
  nyc_airbnb |> 
  mutate(
    borough = fct_infreq(borough), 
    room_type = fct_infreq(room_type) 
  )

fit= lm(price~ stars+ borough, data = nyc_airbnb)



```


Look at `lm` stuff 

```{r, eval=FALSE}
summary(fit)
names(summary(fit))
summary(fit)[["coefficients"]]
summary(fit)[["df"]]

fitted.values(fit)
```

```{r}
fit |> 
  broom::tidy() |>  
  mutate(
    term= str_replace(term, "borough", "Borough: ")
  ) |>  
  select(term, estimate, p.value) |>  
  knitr:: kable(digits=3)

fit |> 
  broom::glance()
```

